name: Compile project

on:
  push:
    branches-ignore:
      - 'master'

jobs:

  test:
    name: Compile Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: JDK Compile
        run: javac src/main/Main.java
      - name: Run program
        run: java src/main/Main
